server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://47.106.168.206:3306/arryn_crud_pgz?=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/master.xml